import express from "express"
import Payment from "../models/Payment.js"
import { verifyToken } from "../middleware/auth.js"

const router = express.Router()

// Get all payments (filtered by userId for regular users, all for admins)
router.get("/", verifyToken, async (req, res) => {
  try {
    let query = {}

    console.log("🔍 GET /payments - userId:", req.userId, "role:", req.role)

    // If admin: return all data
    if (req.role === "admin") {
      // Admin sees all payments
      console.log("👤 Admin user - returning ALL payments")
    } else if (req.userId) {
      // Normal user: return ONLY their own
      query.userId = req.userId
      console.log("✅ Regular user - filtering by userId:", req.userId)
    } else {
      // No userId and not admin: return empty
      console.log("⚠️ No userId identified - returning empty")
      return res.json([])
    }
    
    const payments = await Payment.find(query).sort({ createdAt: -1 }).populate("userId", "username")
    console.log("📊 Found payments:", payments.length)
    res.json(payments)
  } catch (error) {
    console.error("Get payments error:", error)
    res.status(500).json({ message: "Something went wrong." })
  }
})

// Create payment
router.post("/", verifyToken, async (req, res) => {
  try {
    const { farmer, amount, status, date, isAutoGenerated } = req.body

    if (!farmer || !amount || !date) {
      return res.status(400).json({ message: "Required fields missing" })
    }

    // Use userId and username from JWT token (via auth middleware)
    const userId = req.userId
    const userName = req.username

    console.log("Saving payment for userId:", userId)

    const payment = new Payment({
      farmer,
      amount,
      status: status || "Pending",
      date,
      isAutoGenerated: isAutoGenerated || false,
      userId: userId,
      userName: userName
    })

    const savedPayment = await payment.save()
    console.log("✅ Payment saved successfully:", savedPayment)
    await savedPayment.populate("userId", "username")
    res.status(201).json(savedPayment)

  } catch (error) {
    console.error("❌ Create payment error:", error.message)
    res.status(500).json({ message: "Error saving payment: " + error.message })
  }
})

// Update payment status
router.put("/:id", verifyToken, async (req, res) => {
  try {
    const { id } = req.params
    const { status, amount, date } = req.body

    const payment = await Payment.findById(id)
    
    if (!payment) {
      return res.status(404).json({ message: "Payment not found" })
    }

    // Allow update if:
    // 1. User is admin, OR
    // 2. Payment belongs to the user, OR
    // 3. No userId set (backward compatibility)
    const canUpdate = req.role === "admin" || 
                     !req.userId || 
                     (payment.userId && payment.userId.toString() === req.userId)

    if (!canUpdate) {
      return res.status(403).json({ message: "You can only update your own payments" })
    }

    // Update fields
    if (status !== undefined) payment.status = status
    if (amount !== undefined) payment.amount = amount
    if (date !== undefined) payment.date = date

    const updatedPayment = await payment.save()
    console.log("✅ Payment updated:", updatedPayment)
    await updatedPayment.populate("userId", "username")
    res.json(updatedPayment)

  } catch (error) {
    console.error("Update payment error:", error)
    res.status(500).json({ message: "Error updating payment" })
  }
})

// Delete payment
router.delete("/:id", verifyToken, async (req, res) => {
  try {
    const { id } = req.params

    const payment = await Payment.findById(id)

    if (!payment) {
      return res.status(404).json({ message: "Payment not found" })
    }

    // Check authorization
    const canDelete = req.role === "admin" || 
                     !req.userId || 
                     (payment.userId && payment.userId.toString() === req.userId)

    if (!canDelete) {
      return res.status(403).json({ message: "You can only delete your own payments" })
    }

    const deletedPayment = await Payment.findByIdAndDelete(id)
    console.log("✅ Payment deleted:", deletedPayment._id)
    res.json({ message: "Payment deleted", record: deletedPayment })

  } catch (error) {
    console.error("Delete payment error:", error)
    res.status(500).json({ message: "Error deleting payment" })
  }
})

export default router
