import mongoose from "mongoose"

const paymentSchema = new mongoose.Schema({
  farmer: {
    type: String,
    required: true
  },
  amount: {
    type: Number,
    required: true
  },
  status: {
    type: String,
    default: "Pending",
    enum: ["Pending", "Paid", "Approved"]
  },
  date: {
    type: String,
    required: true
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  userId: {
    type: mongoose.Schema.Types.Mixed,
    default: null
  },
  userName: {
    type: String,
    default: null
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
})

const Payment = mongoose.model("Payment", paymentSchema)

export default Payment
